swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api

paths:
  /deploy:
    post:
      summary: Deploy a machine learning model.
      operationId: ml_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
       - "application/json"
      responses:
        200:
          description: prediction response
          schema:
            type: string
          examples:
            "application/json": "OK"
      parameters:
        - in: formData
          name: modelfile
          type: file
          required: true
          description: The machine learning model file to upload.
      responses:
        200:
          description: "Model updated"
        201:
          description: "Model uploaded"
  /predict:
    post:
      summary: Generate predictions
      description: Generate predictions from a given dataframe in a JSON format.
      operationId: ml_service.predict_api
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: prediction response
          schema:
            type: string
          examples:
            "application/json": "[2 2 0]"
      parameters:
        - in: body
          name: data
          description: The data to be sent to the predict api.
          schema:
            type: object
            required:
              - dataframe_json
            properties:
              dataframe_json:
                type: string
                default: "[[6.5,3.0,5.5,1.8],[6.1,3.0,4.9,1.8],[4.8,3.0,1.4,0.1]]"
