swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0.0"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

basePath: /api

paths:
  /get_token:
    post:
      summary: Return secret string
      operationId: ml_service.get_token_api
      produces:
        - "text/plain"
      responses:
        200:
          description: secret response
          schema:
            type: string
      parameters:
        - in: formData
          name: user
          type: string
          required: true
          default: "user"
          description: Returns the token for the user.
      #security:
      #  # enable authentication and require the "uid" scope for this endpoint
      #  - oauth2: ['uid']
  /deploy:
    post:
      summary: Deploy a machine learning model.
      description: Deploy a machine learning model.
      operationId: ml_service.deploy_api
      consumes:
        - "multipart/form-data"
      produces:
        - "application/json"
      responses:
        200:
          description: prediction response
          schema:
            type: string
          examples:
            "application/json": "OK"
      parameters:
        - in: formData
          name: model_file
          type: file
          required: true
          description: The machine learning model file to upload.
        - in: formData
          name: api_token
          type: string
          required: true
          default: "376d873c859d7f9f268e1b9be883745b"
          description: The API token to be sent to the deploy api.
        #- in: body
        #  name: data
        #  description: The API token to be sent to the predict api.
        #  schema:
        #    type: object
        #    required:
        #      - api_token
        #    properties:
        #      api_token:
        #        type: string
        #        default: "376d873c859d7f9f268e1b9be883745b"
      responses:
        200:
          description: "Model updated"
      #security:
      #  # enable authentication and require the "uid" scope for this endpoint
      #  - oauth2: ['uid']
  /predict:
    post:
      summary: Generate predictions
      description: Generate predictions from a given dataframe in a JSON format.
      operationId: ml_service.predict_api
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: prediction response
          schema:
            type: string
          examples:
            "application/json": "[2 2 0]"
      parameters:
        - in: body
          name: data
          description: The data to be sent to the predict api.
          schema:
            type: object
            required:
              - dataframe_json
              - api_token
            properties:
              dataframe_json:
                type: string
                default: "[[6.5,3.0,5.5,1.8],[6.1,3.0,4.9,1.8],[4.8,3.0,1.4,0.1]]"
              api_token:
                type: string
                default: "376d873c859d7f9f268e1b9be883745b"
      #security:
      #  # enable authentication and require the "uid" scope for this endpoint
      #   - oauth2: ['uid']
#securityDefinitions:
#  oauth2:
#    type: oauth2
#    flow: implicit
#    authorizationUrl: https://example.com/oauth2/dialog
#    x-tokenInfoFunc: ml_service.token_info_api
#    scopes:
#      uid: Unique identifier of the user accessing the service.
